// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: internal/api/create_oas.pb

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_create_oas_pb_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_create_oas_pb_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_internal_api_create_oas_pb_rawDescGZIP(), []int{0}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CreateOASRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiKey   string  `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	Language string  `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Spec     []byte  `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Files    []*File `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *CreateOASRequest) Reset() {
	*x = CreateOASRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_create_oas_pb_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOASRequest) ProtoMessage() {}

func (x *CreateOASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_create_oas_pb_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOASRequest.ProtoReflect.Descriptor instead.
func (*CreateOASRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_create_oas_pb_rawDescGZIP(), []int{1}
}

func (x *CreateOASRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateOASRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateOASRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateOASRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type CreateOASResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec string `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *CreateOASResponse) Reset() {
	*x = CreateOASResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_create_oas_pb_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOASResponse) ProtoMessage() {}

func (x *CreateOASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_create_oas_pb_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOASResponse.ProtoReflect.Descriptor instead.
func (*CreateOASResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_create_oas_pb_rawDescGZIP(), []int{2}
}

func (x *CreateOASResponse) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

var File_internal_api_create_oas_pb protoreflect.FileDescriptor

var file_internal_api_create_oas_pb_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x61, 0x73, 0x2e, 0x70, 0x62, 0x12, 0x07, 0x72, 0x6f,
	0x73, 0x65, 0x74, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x7f, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x41, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x23, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x73, 0x65, 0x74, 0x74, 0x61,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x41, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x32, 0x51, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x41,
	0x53, 0x12, 0x19, 0x2e, 0x72, 0x6f, 0x73, 0x65, 0x74, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x41, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72,
	0x6f, 0x73, 0x65, 0x74, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x41, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_create_oas_pb_rawDescOnce sync.Once
	file_internal_api_create_oas_pb_rawDescData = file_internal_api_create_oas_pb_rawDesc
)

func file_internal_api_create_oas_pb_rawDescGZIP() []byte {
	file_internal_api_create_oas_pb_rawDescOnce.Do(func() {
		file_internal_api_create_oas_pb_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_create_oas_pb_rawDescData)
	})
	return file_internal_api_create_oas_pb_rawDescData
}

var file_internal_api_create_oas_pb_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_create_oas_pb_goTypes = []interface{}{
	(*File)(nil),              // 0: rosetta.File
	(*CreateOASRequest)(nil),  // 1: rosetta.CreateOASRequest
	(*CreateOASResponse)(nil), // 2: rosetta.CreateOASResponse
}
var file_internal_api_create_oas_pb_depIdxs = []int32{
	0, // 0: rosetta.CreateOASRequest.files:type_name -> rosetta.File
	1, // 1: rosetta.FileService.CreateOAS:input_type -> rosetta.CreateOASRequest
	2, // 2: rosetta.FileService.CreateOAS:output_type -> rosetta.CreateOASResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_create_oas_pb_init() }
func file_internal_api_create_oas_pb_init() {
	if File_internal_api_create_oas_pb != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_create_oas_pb_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_create_oas_pb_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOASRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_create_oas_pb_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOASResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_create_oas_pb_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_create_oas_pb_goTypes,
		DependencyIndexes: file_internal_api_create_oas_pb_depIdxs,
		MessageInfos:      file_internal_api_create_oas_pb_msgTypes,
	}.Build()
	File_internal_api_create_oas_pb = out.File
	file_internal_api_create_oas_pb_rawDesc = nil
	file_internal_api_create_oas_pb_goTypes = nil
	file_internal_api_create_oas_pb_depIdxs = nil
}
