name: build

on:
  push:
    branches: [ main ]

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: go build ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: userosettadev/rosetta-cli